apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-task-deployment
  labels:
    app: brain-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-task
  template:
    metadata:
      labels:
        app: brain-task
    spec:
      containers:
      - name: brain-task
        image: public.ecr.aws/w7b0v2b2/brain-task:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
