apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-tasks-app
spec:
  selector:
    matchLabels:
      app: brain-tasks-app
  template:
    metadata:
      labels:
        app: brain-tasks-app
    spec:
      containers:
        - name: brain-tasks-app
          image: brain_task:v.1
          ports:
            - containerPort: 80